/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AlbumIdRouteImport } from './routes/album.$id'
import { Route as ArtistIdRouteImport } from './routes/artist.$id'
import { Route as GenreIdRouteImport } from './routes/genre.$id'
import { Route as MoodIdRouteImport } from './routes/mood.$id'
import { Route as PlaylistIdRouteImport } from './routes/playlist.$id'
import { Route as RadioIdRouteImport } from './routes/radio.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumIdRoute = AlbumIdRouteImport.update({
  id: '/album/$id',
  path: '/album/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistIdRoute = ArtistIdRouteImport.update({
  id: '/artist/$id',
  path: '/artist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GenreIdRoute = GenreIdRouteImport.update({
  id: '/genre/$id',
  path: '/genre/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodIdRoute = MoodIdRouteImport.update({
  id: '/mood/$id',
  path: '/mood/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistIdRoute = PlaylistIdRouteImport.update({
  id: '/playlist/$id',
  path: '/playlist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioIdRoute = RadioIdRouteImport.update({
  id: '/radio/$id',
  path: '/radio/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/premium': typeof PremiumRoute
  '/search': typeof SearchRoute
  '/album/$id': typeof AlbumIdRoute
  '/artist/$id': typeof ArtistIdRoute
  '/genre/$id': typeof GenreIdRoute
  '/mood/$id': typeof MoodIdRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/radio/$id': typeof RadioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/premium': typeof PremiumRoute
  '/search': typeof SearchRoute
  '/album/$id': typeof AlbumIdRoute
  '/artist/$id': typeof ArtistIdRoute
  '/genre/$id': typeof GenreIdRoute
  '/mood/$id': typeof MoodIdRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/radio/$id': typeof RadioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/premium': typeof PremiumRoute
  '/search': typeof SearchRoute
  '/album/$id': typeof AlbumIdRoute
  '/artist/$id': typeof ArtistIdRoute
  '/genre/$id': typeof GenreIdRoute
  '/mood/$id': typeof MoodIdRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/radio/$id': typeof RadioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/library'
    | '/premium'
    | '/search'
    | '/album/$id'
    | '/artist/$id'
    | '/genre/$id'
    | '/mood/$id'
    | '/playlist/$id'
    | '/radio/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/library'
    | '/premium'
    | '/search'
    | '/album/$id'
    | '/artist/$id'
    | '/genre/$id'
    | '/mood/$id'
    | '/playlist/$id'
    | '/radio/$id'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/library'
    | '/premium'
    | '/search'
    | '/album/$id'
    | '/artist/$id'
    | '/genre/$id'
    | '/mood/$id'
    | '/playlist/$id'
    | '/radio/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  LibraryRoute: typeof LibraryRoute
  PremiumRoute: typeof PremiumRoute
  SearchRoute: typeof SearchRoute
  AlbumIdRoute: typeof AlbumIdRoute
  ArtistIdRoute: typeof ArtistIdRoute
  GenreIdRoute: typeof GenreIdRoute
  MoodIdRoute: typeof MoodIdRoute
  PlaylistIdRoute: typeof PlaylistIdRoute
  RadioIdRoute: typeof RadioIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$id': {
      id: '/album/$id'
      path: '/album/$id'
      fullPath: '/album/$id'
      preLoaderRoute: typeof AlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$id': {
      id: '/artist/$id'
      path: '/artist/$id'
      fullPath: '/artist/$id'
      preLoaderRoute: typeof ArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genre/$id': {
      id: '/genre/$id'
      path: '/genre/$id'
      fullPath: '/genre/$id'
      preLoaderRoute: typeof GenreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood/$id': {
      id: '/mood/$id'
      path: '/mood/$id'
      fullPath: '/mood/$id'
      preLoaderRoute: typeof MoodIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$id': {
      id: '/playlist/$id'
      path: '/playlist/$id'
      fullPath: '/playlist/$id'
      preLoaderRoute: typeof PlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio/$id': {
      id: '/radio/$id'
      path: '/radio/$id'
      fullPath: '/radio/$id'
      preLoaderRoute: typeof RadioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  LibraryRoute: LibraryRoute,
  PremiumRoute: PremiumRoute,
  SearchRoute: SearchRoute,
  AlbumIdRoute: AlbumIdRoute,
  ArtistIdRoute: ArtistIdRoute,
  GenreIdRoute: GenreIdRoute,
  MoodIdRoute: MoodIdRoute,
  PlaylistIdRoute: PlaylistIdRoute,
  RadioIdRoute: RadioIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
